# Generated by Django 3.1.4 on 2020-12-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nested_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='nested_model.obstacle')),
            ],
        ),
    ]
