# Generated by Django 3.1.4 on 2020-12-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nested_model', '0002_point_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='polygon',
            new_name='obstacle',
        ),
    ]
