# Generated by Django 3.1.4 on 2020-12-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nested_model', '0002_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='obstacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon', to='nested_model.obstacle'),
        ),
    ]
